name: "Repo Traffic Archive"
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  archive-stats:
    runs-on: ubuntu-latest
    steps:
      - name: Run GitHub Repo Stats
        uses: jgehrcke/github-repo-stats@v1.4.2
        with:
          repository: ${{ github.repository }}
          ghtoken: ${{ secrets.TRAFFIC_TOKEN }}
          databranch: github-repo-stats
